{{- if .Values.secret.apiKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodejs-simple-app.apiKeySecretName" . }}
  labels:
    {{- include "nodejs-simple-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.apiKey.value }}
  API_KEY: {{ .Values.secret.apiKey.value | b64enc | quote }}
  {{- end }}
{{- end }}
