apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nodejs-app-gateway
  namespace: default
spec:
  gatewayClassName: nodejs-app-gateway-class
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "api.mohibulalam.xyz"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: api-mohibulalam-xyz-tls
            namespace: default
      allowedRoutes:
        namespaces:
          from: Same
    - name: http
      protocol: HTTP
      port: 80
      hostname: "api.mohibulalam.xyz"
      allowedRoutes:
        namespaces:
          from: Same

