apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: nodejs-app-gateway-class
spec:
  controllerName: gateway.networking.k8s.io/gateway-controller
  description: "Gateway class for nodejs-simple-app"

