apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nodejs-app-httproute
  namespace: default
spec:
  parentRefs:
    - name: nodejs-app-gateway
      namespace: default
      sectionName: https
  hostnames:
    - "api.mohibulalam.xyz"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nodejs-simple-app
          port: 3000
          weight: 100

